server:
  port: 8080
spring:
  application:
    name: "Franchise_MS"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  tracing:
    sampling:
      probability: 0.0
    baggage:
      correlation:
        fields:
          - messageId
      remote-fields: messageId
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
postgres:
  user: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  host: "${DB_HOST}"
  database: "${DB_NAME}"
  port: "${DB_PORT}"
  schema: "${SCHEMA}"
